<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sales</name>
   <tag></tag>
   <elementGuidId>449a262f-70d8-4197-ab55-5ed5eab09851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lgt-accordion-section-154']/slot/div/one-app-launcher-app-tile[8]/div/div[2]/div/a/lightning-formatted-rich-text/span/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>edf63beb-f5e2-43fd-b68b-f67a0299a0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate</value>
      <webElementGuid>bcf54ec9-0b88-4b67-a470-b69faaeedcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales</value>
      <webElementGuid>97b85af3-4637-4d5a-b8e1-0928544df539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lgt-accordion-section-154&quot;)/slot[1]/div[@class=&quot;slds-grid slds-grid_pull-padded slds-wrap app-dnd-identifier&quot;]/one-app-launcher-app-tile[@class=&quot;slds-p-horizontal_small slds-size_1-of-1 slds-small-size_1-of-1 slds-medium-size_1-of-2 slds-large-size_1-of-3&quot;]/div[@class=&quot;slds-app-launcher__tile slds-text-link_reset slds-is-draggable&quot;]/div[@class=&quot;slds-app-launcher__tile-body slds-truncate&quot;]/div[@class=&quot;slds-truncate&quot;]/a[@class=&quot;slds-text-heading_small&quot;]/lightning-formatted-rich-text[@class=&quot;slds-rich-text-editor__output&quot;]/span[1]/p[@class=&quot;slds-truncate&quot;]</value>
      <webElementGuid>04ea2b35-af3e-418c-b5a2-30b29444012e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lgt-accordion-section-154']/slot/div/one-app-launcher-app-tile[8]/div/div[2]/div/a/lightning-formatted-rich-text/span/p</value>
      <webElementGuid>f484c530-928d-4dc3-9c2c-03f946183f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reorder'])[7]/following::p[1]</value>
      <webElementGuid>2000c6f3-bddb-464c-8f8a-503f0ea582c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reorder'])[6]/following::p[3]</value>
      <webElementGuid>2da99d0c-9f25-4010-bb56-6c070c372162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reorder'])[8]/preceding::p[2]</value>
      <webElementGuid>32449f0c-64c2-4215-9d9b-9227a1a95ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reorder'])[9]/preceding::p[4]</value>
      <webElementGuid>001eac4f-c1f0-43fe-ad12-5132af17cd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sales']/parent::*</value>
      <webElementGuid>84eaff70-9c55-454c-ab0e-6bc2e8f27ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-app-tile[8]/div/div[2]/div/a/lightning-formatted-rich-text/span/p</value>
      <webElementGuid>55758379-8798-47c6-9a16-b31af64f58d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sales' or . = 'Sales')]</value>
      <webElementGuid>5160deba-ccd1-4c19-83fc-c8e808654385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
