<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-primitive-icon</name>
   <tag></tag>
   <elementGuidId>ce9283d6-4cc8-4dbd-8113-699450f7247f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-button-icon.slds-panel__close > button.slds-button.slds-button_icon.slds-button_icon-bare > lightning-primitive-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='window']/slot/div/div/lightning-button-icon[3]/button/lightning-primitive-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-primitive-icon</value>
      <webElementGuid>8347ccd5-8f49-462b-8dcf-2c063798118f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>89d05fe5-1a1a-485b-ab01-2fde237edfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>bare</value>
      <webElementGuid>b285f6f8-09ac-402f-aeaa-7696f5e05ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;window&quot;)/slot[1]/div[1]/div[@class=&quot;sidebarHeader slds-panel__header slds-panel__header_custom slds-shrink-none slds-grow-none&quot;]/lightning-button-icon[@class=&quot;slds-panel__close&quot;]/button[@class=&quot;slds-button slds-button_icon slds-button_icon-bare&quot;]/lightning-primitive-icon[1]</value>
      <webElementGuid>c234bda3-5752-4633-8cf0-775430ecfc59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='window']/slot/div/div/lightning-button-icon[3]/button/lightning-primitive-icon</value>
      <webElementGuid>5dd36979-cc0e-4699-9b04-e5ba311a5ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[4]/following::lightning-primitive-icon[1]</value>
      <webElementGuid>b5a86eec-81c2-49ac-ade8-bfe7cae5d4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::lightning-primitive-icon[1]</value>
      <webElementGuid>5688adc5-f52b-49f9-b57c-04d1e2f94dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::lightning-primitive-icon[1]</value>
      <webElementGuid>f9ba15aa-f1a6-45eb-b9a7-5455ba69b75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Just so you know'])[1]/preceding::lightning-primitive-icon[1]</value>
      <webElementGuid>30e14130-96b6-43e1-b0b0-9b0a34932a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-button-icon[3]/button/lightning-primitive-icon</value>
      <webElementGuid>0667742f-1184-46ea-8d03-fd9c9b17831f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
