<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name</name>
   <tag></tag>
   <elementGuidId>2c7e2d72-ea51-4db6-9f98-a3c543c83cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;input-195&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-247</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b36010dd-b1c7-436d-8911-a2eed8713fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>3c4bbca2-4760-499c-b7c8-9861fcb0108c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e638c1e1-5d10-47f2-be56-21baf698da5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-247</value>
      <webElementGuid>5d1b1d3e-061a-421f-bbfb-9c43a0b2b626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>dd229b3b-6a61-4740-a8cd-8a828ba38cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>079fe568-6616-4e92-9a28-f8ca968fec6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f571daba-e958-4cea-8ca7-b44c7bfcb10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-message-247</value>
      <webElementGuid>1b970d7b-d80e-451e-b627-a45925e9af46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-247&quot;)</value>
      <webElementGuid>80ef16a5-0123-490b-b310-470fad38b019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-247']</value>
      <webElementGuid>3b7a2c0c-1a65-414b-9297-31103a789716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-230']/dl/slot/records-record-layout-row[2]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>d268cdd5-61ef-45ce-a39d-509445d3bd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>a9a6fbe4-3a86-40a0-8bee-9eb9fe976124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-247' and @name = 'Name' and @type = 'text']</value>
      <webElementGuid>38a3f9d8-d1a6-4760-9c41-700d40cfc57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-358']</value>
      <webElementGuid>f630f3a8-ef71-433b-bdea-1e1e4d52cf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-341']/dl/slot/records-record-layout-row[2]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>1be4e426-b85b-4924-970c-2012d114670f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-358' and @name = 'Name' and @type = 'text']</value>
      <webElementGuid>1208a0a1-a1c1-46b3-938a-c556e8f3ebd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
