<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name</name>
   <tag></tag>
   <elementGuidId>2c7e2d72-ea51-4db6-9f98-a3c543c83cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-358</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-358']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2db8792-7a78-41c3-b68c-87e9b6e83a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>c3a4067d-342c-42f1-a79f-0a396b956ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ce3c8f7-6e4e-440a-858a-918791c729be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-358</value>
      <webElementGuid>ec568725-9db5-4039-a746-93b729d9e2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>40b86190-f56a-404a-bfcd-b0d24009959e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>974156c4-9989-4585-8176-2f666a7c087e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbfcfdd1-7721-40ac-bf83-59dea4191a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-message-358</value>
      <webElementGuid>bc200797-51c6-483a-81ea-123f49baa3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-358&quot;)</value>
      <webElementGuid>e56fe49f-612f-49a6-8116-d58b2e828180</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-358']</value>
      <webElementGuid>fd83a163-20ac-4d79-851f-9032f55d8f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-341']/dl/slot/records-record-layout-row[2]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>6e2fd7dc-a942-44c7-b5d5-ea81b80adbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>9372695d-73c1-4990-94a0-fcfbd4cc73a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-358' and @name = 'Name' and @type = 'text']</value>
      <webElementGuid>cd9939e3-11db-4368-bee7-a446b887f1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-247']</value>
      <webElementGuid>b3048452-efa3-44c5-ad7c-383e94d096f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-230']/dl/slot/records-record-layout-row[2]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>9805a951-882b-4628-9e25-e031155265dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-247' and @name = 'Name' and @type = 'text']</value>
      <webElementGuid>3450d748-4d0f-405d-9acb-494a57108e99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
