<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verification Code_emc</name>
   <tag></tag>
   <elementGuidId>c62e091c-d6f5-4e56-9103-888d9b5cde6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6abb021-0a11-42a6-93ee-c068a494e5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input wide mb8 mt8 focus</value>
      <webElementGuid>4ffac11e-02e4-45e0-a748-35216de60bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e7c4c5c5-3799-4d84-b93b-0d4b0287f6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emc</value>
      <webElementGuid>f9f9b7e3-aea2-4b88-af70-48a08e4fc219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>aa6e1af7-307a-430e-a242-7710be72413f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emc</value>
      <webElementGuid>240a6e22-c8d6-4b78-a8af-b1609aecbebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b67d53ec-6835-4675-b3ed-211a22d8a966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e8288cf-2528-4500-8ce1-f9813791b516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user-scalable</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d2607469-157f-4027-a366-30783ad32a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>​aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e8c4861-db92-47f7-979a-da11e27c60ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emc&quot;)</value>
      <webElementGuid>91efe3a4-7432-484d-8628-56325b545bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emc']</value>
      <webElementGuid>2cc07423-f490-41f2-ae10-2acd95d594ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editPage']/div/input</value>
      <webElementGuid>1f26b2f0-6153-4974-857f-eaf39533f706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f06eb861-0336-49b3-8707-d0e365bd63e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emc' and @name = 'emc' and @type = 'text']</value>
      <webElementGuid>a483293b-efc0-4b99-8e90-f4c4500c340f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
