<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verification Code_save</name>
   <tag></tag>
   <elementGuidId>4794debf-a22a-4039-a4dc-0b01b512db35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>280a9f83-b7df-4376-bd86-d307758d9b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>dcbd3145-6bd6-45d2-a047-1f473f217348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary wide mt8 mb16</value>
      <webElementGuid>b3848d7b-3bf8-4dcd-939d-cc98171aa1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>bd044e69-a77d-49c8-a80f-559a5fc140c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>b8ac11c6-6fd9-466e-917f-19a55b27ef87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>0fb4b41c-47da-4e8c-8236-025a07e34ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5728cee3-13f9-4a24-99fb-5dbb1e3aae90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save&quot;)</value>
      <webElementGuid>52dccf8a-f2e9-4cba-b186-84cdca60c438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='save']</value>
      <webElementGuid>169a4b48-7f07-4e1f-a059-13159dd9c62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editPage']/input[10]</value>
      <webElementGuid>0016f5e2-6bf7-4caf-9883-e4eec8a4f647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>73a46c95-2c72-4ef9-bf3c-1614f8fb6258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'save' and @name = 'save' and @title = 'Verify' and @type = 'submit']</value>
      <webElementGuid>c913a939-e849-4896-96b1-c0a2bd288669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
