<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Clone</name>
   <tag></tag>
   <elementGuidId>9957ffc1-7b04-4e7a-8578-5e2a509f4319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_neutral.slds-button_first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59630924-1a74-4fda-864b-2622d59c4c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_neutral slds-button_first</value>
      <webElementGuid>46adbacb-5956-41f3-a41a-8b5c5f58f6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9fa949a5-cacc-4d7e-8a4f-59455baca5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Clone for the rest of the days of the week</value>
      <webElementGuid>fcf223cc-8ff7-484c-adfc-f9a001f9b336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2c05185-6b0e-44fe-b6b0-5fc53ccec325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b08f5182-77d3-4122-83f3-c022a8fdced3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clone</value>
      <webElementGuid>67c824bb-9410-4bdd-af03-f859f88c3dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lgt-accordion-section-37&quot;)/slot[1]/table[@class=&quot;slds-table slds-table_bordered&quot;]/tbody[1]/tr[1]/td[6]/div[@class=&quot;slds-truncate optionsCol&quot;]/lightning-button-group[@class=&quot;slds-button-group&quot;]/div[@class=&quot;fix_button-group-flexbox&quot;]/slot[1]/lightning-button[@class=&quot;slds-m-right_small&quot;]/button[@class=&quot;slds-button slds-button_neutral slds-button_first&quot;]</value>
      <webElementGuid>2f8bb112-b914-4d12-b3e3-44f186561fe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>46645a03-3304-4540-83a8-0ed8026f49aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lgt-accordion-section-37']/slot/table/tbody/tr/td[6]/div/lightning-button-group/div/slot/lightning-button/button</value>
      <webElementGuid>6b6af5d5-b91c-416f-8e48-0e120ce10052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::button[1]</value>
      <webElementGuid>5b03d2d4-e5b3-4711-91ef-1e65a5adb196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::button[1]</value>
      <webElementGuid>ae66f97e-320b-49ad-a1d7-004473834185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::button[1]</value>
      <webElementGuid>9e09a797-64b6-4e63-9506-ae2ff2f990ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::button[2]</value>
      <webElementGuid>f40642b5-4eb9-4505-b46e-c650f43b47aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clone']/parent::*</value>
      <webElementGuid>42e088dc-c0e2-4ef6-acec-0eddb2f7d133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-button/button</value>
      <webElementGuid>20260a73-143a-4276-9a1b-380ec0dd0d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Clone for the rest of the days of the week' and @type = 'button' and (text() = 'Clone' or . = 'Clone')]</value>
      <webElementGuid>6cb51d1d-10c4-49de-8ed1-a56c6b97d47c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
