<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_QA</name>
   <tag></tag>
   <elementGuidId>1e27fe4f-7fe5-45c6-9f4a-d752ac3ac570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-46-6-46']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-46-6-46 > span.slds-media__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>57584de3-4c8a-4cf9-a54f-67d74dc04053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>a7b77da8-a73f-476e-998a-cc3b3eb12747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QA</value>
      <webElementGuid>76daa630-a791-410d-85fd-6b3283e92bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-46-6-46&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>ac54acfc-5f19-4186-b20d-bb7ad18054bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-46-6-46']/span[2]</value>
      <webElementGuid>81a681c5-7e83-484f-b389-5246de3ddc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Management'])[1]/following::span[2]</value>
      <webElementGuid>9e77a93b-c73c-4498-b7bd-4cd183fe8db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Enablement'])[1]/following::span[5]</value>
      <webElementGuid>f0cab60a-08a6-4394-8b81-760135a5df90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SW-Response Management'])[1]/preceding::span[3]</value>
      <webElementGuid>9c721c22-a865-4c20-ae92-1670db55296d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[7]/span[2]</value>
      <webElementGuid>aef9cdae-44f5-41bc-b971-cfc7cbb2432e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'QA' or . = 'QA')]</value>
      <webElementGuid>9b36d678-3e0b-4556-88c8-93350263ce88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
